--create database QL
--use master
--drop database QL
use QL
set dateformat DMY


CREATE TABLE BOPHIM (
    MAPHIM CHAR(4) PRIMARY KEY,
    TENPHIM NVARCHAR(100) NOT NULL,
    THELOAI VARCHAR(30) NOT NULL,
    THOILUONG INT NOT NULL,
    MOTA NVARCHAR(500),
    --NAMPHATHANH INT,
    --DAODIEN NVARCHAR(50),
    --DIENVIENCHINH NVARCHAR(255),
    --NHASANXUAT NVARCHAR(100),
    --NGONNGU NVARCHAR(50),
    --GIOIHANDOTUOI INT,
    POSTER_URL VARCHAR(255),
    TRAILER_URL VARCHAR(255)
);

CREATE TABLE PHONGCHIEU (
    MAPHONG CHAR(4) PRIMARY KEY,
    SOGHE INT NOT NULL,
    LOAIPHONG VARCHAR(10) CHECK (LOAIPHONG IN ('2D', '3D', '4D', 'IMAX')),
	GIA INT NOT NULL
);

CREATE TABLE SUATCHIEU (
    MASUATCHIEU CHAR(4) PRIMARY KEY,
    THOIGIANBATDAU DATETIME NOT NULL,
    THOIGIANKETTHUC DATETIME NOT NULL,
    MAPHONG CHAR(4) NOT NULL,
    MAPHIM CHAR(4) NOT NULL,
    FOREIGN KEY (MAPHONG) REFERENCES PHONGCHIEU(MAPHONG),
    FOREIGN KEY (MAPHIM) REFERENCES BOPHIM(MAPHIM)
);


CREATE TABLE TAIKHOANTHANHVIEN (
    MATAIKHOAN CHAR(4) PRIMARY KEY,
    MAKHACHHANG CHAR(4) NOT NULL,
    NGAYDANGKY DATE NOT NULL,
    DIEMTICHLUY INT DEFAULT 0,
    HANGTHANHVIEN NVARCHAR(10) CHECK (HANGTHANHVIEN IN ('Thường', 'Bạc', 'Vàng', 'Kim Cương')),
    QUYENLOI NVARCHAR(255),
   
);

CREATE TABLE KHACHHANG (
    MAKHACHHANG CHAR(4) PRIMARY KEY,
    TENKHACHHANG NVARCHAR(50) NOT NULL,
    SODIENTHOAI VARCHAR(15),
    EMAIL VARCHAR(50),
    --NGAYSINH DATE,
    TAIKHOANTHANHVIEN CHAR(4), 
    DIEMTICHLUY INT DEFAULT 0,
    FOREIGN KEY (TAIKHOANTHANHVIEN) REFERENCES TAIKHOANTHANHVIEN(MATAIKHOAN)
);


CREATE TABLE VE (
    MAVE CHAR(4) PRIMARY KEY,
    MASUATCHIEU CHAR(4) NOT NULL,
    SOGHE INT NOT NULL,
    MAKHACHHANG CHAR(4) NOT NULL,
    SUM_GIA DECIMAL(10, 2) NOT NULL,
    FOREIGN KEY (MASUATCHIEU) REFERENCES SUATCHIEU(MASUATCHIEU),
    FOREIGN KEY (MAKHACHHANG) REFERENCES KHACHHANG(MAKHACHHANG)
);

CREATE TABLE NHANVIEN (
    MANHANVIEN CHAR(4) PRIMARY KEY,
    TENNHANVIEN NVARCHAR(100) NOT NULL,
    CHUCVU NVARCHAR(50) NOT NULL,
    SODIENTHOAI VARCHAR(15),
    EMAIL VARCHAR(50),
    DIACHI NVARCHAR(255),
    LUONG DECIMAL(10, 2),
    --NGAYBATDAULAM DATE NOT NULL,
    TRANGTHAI NVARCHAR(20) CHECK (TRANGTHAI IN ('Đang làm việc', 'Nghỉ việc', 'Tạm thời')),
    --GIOLAMVIEN NVARCHAR(50),
    --CHUNGCHI NVARCHAR(255),
    --LICHSUCONGVIEC NVARCHAR(255)
);

--CREATE TABLE CALAMVIEN (
--    MACA CHAR(4) PRIMARY KEY,
--    MANHANVIEN CHAR(4) NOT NULL,
--    THOIGIANBATDAU TIME NOT NULL,
--    THOIGIANKETTHUC TIME NOT NULL,
--    NGAYLAMVIEN DATE NOT NULL,
--    FOREIGN KEY (MANHANVIEN) REFERENCES NHANVIEN(MANHANVIEN)
--);

--CREATE TABLE THIETBI (
--    MATHIETBI CHAR(4) PRIMARY KEY,
--    TENTHIETBI NVARCHAR(100) NOT NULL,
--    LOAITHIETBI NVARCHAR(50) NOT NULL,
--    MOTA NVARCHAR(255),
--    TRANGTHAI NVARCHAR(20) CHECK (TRANGTHAI IN ('Đang sử dụng', 'Bảo trì', 'Hỏng hóc')),
--    NGAYMUA DATE NOT NULL,
--    THOIGIANBAOHANH INT,
--    NHACUNGCAP NVARCHAR(100),
--    DIACHI NVARCHAR(255),
--    SODIENTHOAI VARCHAR(15),
--    CHIPHI DECIMAL(10, 2),
--    VITRI NVARCHAR(100)
--);

--CREATE TABLE BAOTRI (
--    MABAO_TRI CHAR(4) PRIMARY KEY,
--    MATHIETBI CHAR(4) NOT NULL,
--    NGAYBAOTRI DATE NOT NULL,
--    MOTA NVARCHAR(255),
--    MANHANVIEN CHAR(4) NOT NULL,
--    TRANGTHAI VARCHAR(20) CHECK (TRANGTHAI IN ('Đang thực hiện', 'Hoàn thành')),
--    FOREIGN KEY (MATHIETBI) REFERENCES THIETBI(MATHIETBI),
--    FOREIGN KEY (MANHANVIEN) REFERENCES NHANVIEN(MANHANVIEN)
--);

--CREATE TABLE LICHLAMVIEC (
--    MALICH CHAR(4) PRIMARY KEY,
--    MANHANVIEN CHAR(4) NOT NULL,
--    NGAYLAMVIEC DATE NOT NULL,
--    MACA CHAR(4) NOT NULL,
--    NHIEMVU NVARCHAR(255),
--    FOREIGN KEY (MANHANVIEN) REFERENCES NHANVIEN(MANHANVIEN),
--    FOREIGN KEY (MACA) REFERENCES CALAMVIEN(MACA)
--);

--CREATE TABLE DAOTAO (
--    MAKHOADAOTAO CHAR(4) PRIMARY KEY,
--    TENKHOADAOTAO NVARCHAR(100) NOT NULL,
--    NOIDUNG NVARCHAR(255),
--    NGAYBATDAU DATE NOT NULL,
--    NGAYKETTHUC DATE NOT NULL,
--    GIANGVIEN NVARCHAR(100),
--    MANHANVIEN CHAR(4) NOT NULL,
--    FOREIGN KEY (MANHANVIEN) REFERENCES NHANVIEN(MANHANVIEN)
--);

--CREATE TABLE DANHGIAHIEUSUAT (
--    MADANHGIA CHAR(4) PRIMARY KEY,
--    MANHANVIEN CHAR(4) NOT NULL,
--    NGAYDANHGIA DATE NOT NULL,
--    TIUCHIDANHGIA NVARCHAR(255),
--    DIEMDANHGIA INT CHECK (DIEMDANHGIA BETWEEN 1 AND 5),
--    NHANXET NVARCHAR(255),
--    FOREIGN KEY (MANHANVIEN) REFERENCES NHANVIEN(MANHANVIEN)
--);

--CREATE TABLE DANHGIA (
--    MADANHGIA CHAR(4) PRIMARY KEY,
--    MAPHIM CHAR(4) NOT NULL,
--    MAKHACHHANG CHAR(4) NOT NULL,
--    NOIDUNGDANHGIA NVARCHAR(255),
--    DIEMDANHGIA INT CHECK (DIEMDANHGIA BETWEEN 1 AND 5),
--    NGAYDANHGIA DATE NOT NULL,
--    FOREIGN KEY (MAPHIM) REFERENCES BOPHIM(MAPHIM),
--    FOREIGN KEY (MAKHACHHANG) REFERENCES KHACHHANG(MAKHACHHANG)
--);

--CREATE TABLE KHUYENMAI (
--    MAKHUYENMAI CHAR(4) PRIMARY KEY,
--    TENKHUYENMAI NVARCHAR(100) NOT NULL,
--    LOAIKHUYENMAI VARCHAR(20) CHECK (LOAIKHUYENMAI IN ('Giảm giá', 'Tặng quà')),
--    MOTA NVARCHAR(255),
--    NGAYBATDAU DATE NOT NULL,
--    NGAYKETTHUC DATE NOT NULL,
--    DIEUKIENAPDUNG NVARCHAR(255),
--	MASUATCHIEU CHAR(4) NULL REFERENCES SUATCHIEU(MASUATCHIEU)
--);
CREATE TABLE VOUCHER (
	MAPHATHANH CHAR(16) PRIMARY KEY,
	MENHGIA INT NOT  NULL,
	TRANGTHAI NVARCHAR(20) CHECK (TRANGTHAI IN ('Còn hạn', 'Hết hạn')),
);
CREATE TABLE SUCO (
	MABAOCAO CHAR(16) PRIMARY KEY,
	MANHANVIEN CHAR(4) REFERENCES NHANVIEN(MANHANVIEN),
	TINHTRANG NVARCHAR(20) CHECK (TINHTRANG IN ('Đang xử lý', 'Chờ xử lý', 'Đã xử lý')),
	NGAYBAOCAO DATE NOT NULL
);
--ALTER TABLE KHUYENMAI ADD MASUATCHIEU CHAR(4) NULL
--ALTER TABLE KHUYENMAI ADD FOREIGN KEY (MASUATCHIEU) REFERENCES SUATCHIEU(MASUATCHIEU)
--ALTER TABLE SUATCHIEU ALTER COLUMN THOIGIANBATDAU TIME  NOT NULL
--ALTER TABLE SUATCHIEU ALTER COLUMN THOIGIANKETTHUC TIME  NOT NULL
--DROP TABLE DAOTAO